name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: cache executed notebooks
        uses: actions/cache@v3
        with:
          path: _build/.jupyter_cache
          key: jupyter-book-cache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('**/*.ipynb') }}

      - name: Build the book
        run: |
          jupyter-book build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: _build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          name: book-html
          path: _build/html
